### ISSUE TITLE
tile.fluid.pump and modid：cyclicmagic

### ISSUE THREAD

**Issue by Shousakura** [DarkPacks/SkyFactory-4#1120]
[15:46:47] [pool-3-thread-1/INFO] [toastcontrol]: class matteroverdrive.handler.thread.RegistryToast
[15:46:47] [pool-3-thread-1/INFO] [toastcontrol]: class matteroverdrive.handler.thread.RegistryToast
[15:47:00] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
	at com.lothrazar.cyclicmagic.block.cablepump.fluid.TileEntityFluidPump.func_73660_a(TileEntityFluidPump.java:96) ~[TileEntityFluidPump.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1835) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
[15:47:04] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: F:\MultiMC\instances\SkyFactory4-4.0.8\minecraft\crash-reports\crash-2019-07-04_15.47.04-server.txt
[15:47:04] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[15:47:04] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[15:47:04] [Client thread/INFO] [journeymap]: Mapping halted in F:\MultiMC\instances\SkyFactory4-4.0.8\minecraft\journeymap\data\sp\~\DIM0
[15:47:04] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[15:47:04] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level '新的世界'/DIM_0
[15:47:04] [Netty Local Client IO #0/INFO] [EnderCore]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[15:47:04] [Netty Local Client IO #0/INFO] [Astral Sorcery]: Cleaning client cache...
[15:47:05] [Netty Local Client IO #0/INFO] [Astral Sorcery]: Cleared cached client data! Disconnected from server.
[15:47:05] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level '新的世界'/Storage Cell
[15:47:05] [Server thread/INFO] [FML]: Unloading dimension 0
[15:47:05] [Server thread/INFO] [FML]: Unloading dimension 2
[15:47:06] [Server thread/INFO] [foamfix]: JEI search tree manager injection complete!
[15:47:06] [Server thread/INFO] [FML]: Applying holder lookups
[15:47:06] [Server thread/INFO] [FML]: Holder lookups applied
[15:47:06] [Server thread/INFO] [fluxnetworks]: FluxNetworkData has been unloaded
[15:47:06] [Server thread/INFO] [fluxnetworks]: Cleared Network Caches
[15:47:06] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up all world data: 1 data blobs
[15:47:06] [Server thread/INFO] [nuclearcraft]: Server Closing...
[15:47:06] [Server thread/INFO] [Parabox]: Saving Parabox world data.
[15:47:06] [Server thread/INFO] [practicallogistics2]: Cleared Server Info Handler
[15:47:06] [Server thread/INFO] [practicallogistics2]: Cleared Network Handler
[15:47:06] [Server thread/INFO] [practicallogistics2]: Cleared Data Factory
[15:47:07] [Server thread/INFO] [practicallogistics2]: Cleared Wireless Data Manager
[15:47:07] [Server thread/INFO] [practicallogistics2]: Cleared Wireless Redstone Manager
[15:47:07] [Server thread/INFO] [practicallogistics2]: Cleared Cable Connection Handler
[15:47:07] [Server thread/INFO] [practicallogistics2]: Cleared Redstone Connection Handler
[15:47:07] [Server thread/INFO] [practicallogistics2]: Cleared Server Display Handler
[15:47:07] [Server thread/INFO] [practicallogistics2]: Cleared Chunk Viewer Handler
[15:47:07] [Server thread/INFO] [practicallogistics2]: Cleared Client Info Handler
[15:47:07] [Server thread/INFO] [topography]: Cleaning up
[15:47:07] [Server thread/INFO] [topography]: Unregistering Dimension 0
[15:47:07] [Server thread/INFO] [topography]: Registering Dimension 0
[15:47:07] [Server thread/INFO] [topography]: Unregistering Dimension -1
[15:47:07] [Server thread/INFO] [topography]: Registering Dimension -1
[15:47:07] [Server thread/INFO] [topography]: Done clean-up
[15:47:07] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/Darkosto/SkyFactory4Issues/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
