### ISSUE TITLE
My Minecraft won't load!

### ISSUE THREAD

**Issue by WwAaSsU** [DarkPacks/SkyFactory-4#1137]
When I press play to "play" the mod it doesnt actually work and it just gives me this message:
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Darkosto** [comment]
This sounds like your Java isn't setup correctly. This is not a modpack issue, this is something you need to take care of on your end.
