### ISSUE TITLE
Launching Issue

### ISSUE THREAD

**Issue by Bango1324** [DarkPacks/SkyFactory-4#1166]
## Bug Report

whenever i try to launch it says "Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)"

## Expected Behaviour

it doesnt let me open the the game instead of launching

## Steps to Reproduce (for bugs)

1.launch Minecraft

## Logs

[14:26:20 INFO]: Minecraft Launcher 1.6.91 (through bootstrap 100) started on osx...
[14:26:20 INFO]: Current time is Aug 3, 2019, 2:26:20 PM
[14:26:20 INFO]: System.getProperty('os.name') == 'Mac OS X'
[14:26:20 INFO]: System.getProperty('os.version') == '10.13.6'
[14:26:20 INFO]: System.getProperty('os.arch') == 'x86_64'
[14:26:20 INFO]: System.getProperty('java.version') == '11.0.1'
[14:26:20 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[14:26:20 INFO]: System.getProperty('sun.arch.data.model') == '64'
[14:26:20 INFO]: proxy == DIRECT
[14:26:21 INFO]: Refreshing local version list...
[14:26:21 INFO]: Refreshing remote version list...
[14:26:21 INFO]: Refresh complete.
[14:26:22 INFO]: Installed CompleteVersion{id='1.10.2', updatedTime=Thu Jun 23 05:17:32 EDT 2016, releasedTime=Thu Jun 23 05:17:32 EDT 2016, type=RELEASE, libraries=[Library{name='com.mojang:netty:1.6', rules=null, natives=null, extract=null}, Library{name='oshi-project:oshi-core:1.1', rules=null, natives=null, extract=null}, Library{name='net.java.dev.jna:jna:3.4.0', rules=null, natives=null, extract=null}, Library{name='net.java.dev.jna:platform:3.4.0', rules=null, natives=null, extract=null}, Library{name='com.ibm.icu:icu4j-core-mojang:51.2', rules=null, natives=null, extract=null}, Library{name='net.sf.jopt-simple:jopt-simple:4.6', rules=null, natives=null, extract=null}, Library{name='com.paulscode:codecjorbis:20101023', rules=null, natives=null, extract=null}, Library{name='com.paulscode:codecwav:20101023', rules=null, natives=null, extract=null}, Library{name='com.paulscode:libraryjavasound:20101123', rules=null, natives=null, extract=null}, Library{name='com.paulscode:librarylwjglopenal:20100824', rules=null, natives=null, extract=null}, Library{name='com.paulscode:soundsystem:20120107', rules=null, natives=null, extract=null}, Library{name='io.netty:netty-all:4.0.23.Final', rules=null, natives=null, extract=null}, Library{name='com.google.guava:guava:17.0', rules=null, natives=null, extract=null}, Library{name='org.apache.commons:commons-lang3:3.3.2', rules=null, natives=null, extract=null}, Library{name='commons-io:commons-io:2.4', rules=null, natives=null, extract=null}, Library{name='commons-codec:commons-codec:1.9', rules=null, natives=null, extract=null}, Library{name='net.java.jinput:jinput:2.0.5', rules=null, natives=null, extract=null}, Library{name='net.java.jutils:jutils:1.0.0', rules=null, natives=null, extract=null}, Library{name='com.google.code.gson:gson:2.2.4', rules=null, natives=null, extract=null}, Library{name='com.mojang:authlib:1.5.22', rules=null, natives=null, extract=null}, Library{name='com.mojang:realms:1.9.8', rules=null, natives=null, extract=null}, Library{name='org.apache.commons:commons-compress:1.8.1', rules=null, natives=null, extract=null}, Library{name='org.apache.httpcomponents:httpclient:4.3.3', rules=null, natives=null, extract=null}, Library{name='commons-logging:commons-logging:1.1.3', rules=null, natives=null, extract=null}, Library{name='org.apache.httpcomponents:httpcore:4.3.2', rules=null, natives=null, extract=null}, Library{name='it.unimi.dsi:fastutil:7.0.12_mojang', rules=null, natives=null, extract=null}, Library{name='org.apache.logging.log4j:log4j-api:2.0-beta9', rules=null, natives=null, extract=null}, Library{name='org.apache.logging.log4j:log4j-core:2.0-beta9', rules=null, natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives={LINUX=natives-linux, OSX=natives-osx, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@6938029c}, Library{name='org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives={LINUX=natives-linux, OSX=natives-osx, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@9cab270}, Library{name='net.java.jinput:jinput-platform:2.0.5', rules=null, natives={LINUX=natives-linux, OSX=natives-osx, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@3515e573}], mainClass='net.minecraft.client.main.Main', jar='null', minimumLauncherVersion=18}
[14:26:22 INFO]: Installed CompleteVersion{id='1.10.2', updatedTime=Thu Jun 23 05:17:32 EDT 2016, releasedTime=Thu Jun 23 05:17:32 EDT 2016, type=RELEASE, libraries=[Library{name='com.mojang:netty:1.6', rules=null, natives=null, extract=null}, Library{name='oshi-project:oshi-core:1.1', rules=null, natives=null, extract=null}, Library{name='net.java.dev.jna:jna:3.4.0', rules=null, natives=null, extract=null}, Library{name='net.java.dev.jna:platform:3.4.0', rules=null, natives=null, extract=null}, Library{name='com.ibm.icu:icu4j-core-mojang:51.2', rules=null, natives=null, extract=null}, Library{name='net.sf.jopt-simple:jopt-simple:4.6', rules=null, natives=null, extract=null}, Library{name='com.paulscode:codecjorbis:20101023', rules=null, natives=null, extract=null}, Library{name='com.paulscode:codecwav:20101023', rules=null, natives=null, extract=null}, Library{name='com.paulscode:libraryjavasound:20101123', rules=null, natives=null, extract=null}, Library{name='com.paulscode:librarylwjglopenal:20100824', rules=null, natives=null, extract=null}, Library{name='com.paulscode:soundsystem:20120107', rules=null, natives=null, extract=null}, Library{name='io.netty:netty-all:4.0.23.Final', rules=null, natives=null, extract=null}, Library{name='com.google.guava:guava:17.0', rules=null, natives=null, extract=null}, Library{name='org.apache.commons:commons-lang3:3.3.2', rules=null, natives=null, extract=null}, Library{name='commons-io:commons-io:2.4', rules=null, natives=null, extract=null}, Library{name='commons-codec:commons-codec:1.9', rules=null, natives=null, extract=null}, Library{name='net.java.jinput:jinput:2.0.5', rules=null, natives=null, extract=null}, Library{name='net.java.jutils:jutils:1.0.0', rules=null, natives=null, extract=null}, Library{name='com.google.code.gson:gson:2.2.4', rules=null, natives=null, extract=null}, Library{name='com.mojang:authlib:1.5.22', rules=null, natives=null, extract=null}, Library{name='com.mojang:realms:1.9.8', rules=null, natives=null, extract=null}, Library{name='org.apache.commons:commons-compress:1.8.1', rules=null, natives=null, extract=null}, Library{name='org.apache.httpcomponents:httpclient:4.3.3', rules=null, natives=null, extract=null}, Library{name='commons-logging:commons-logging:1.1.3', rules=null, natives=null, extract=null}, Library{name='org.apache.httpcomponents:httpcore:4.3.2', rules=null, natives=null, extract=null}, Library{name='it.unimi.dsi:fastutil:7.0.12_mojang', rules=null, natives=null, extract=null}, Library{name='org.apache.logging.log4j:log4j-api:2.0-beta9', rules=null, natives=null, extract=null}, Library{name='org.apache.logging.log4j:log4j-core:2.0-beta9', rules=null, natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives={LINUX=natives-linux, OSX=natives-osx, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@63899ff9}, Library{name='org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives={LINUX=natives-linux, OSX=natives-osx, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@a777838}, Library{name='net.java.jinput:jinput-platform:2.0.5', rules=null, natives={LINUX=natives-linux, OSX=natives-osx, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@63977ca4}], mainClass='net.minecraft.client.main.Main', jar='null', minimumLauncherVersion=18}
[14:26:22 INFO]: Installed CompleteVersion{id='1.12.2', updatedTime=Mon Sep 18 04:39:46 EDT 2017, releasedTime=Mon Sep 18 04:39:46 EDT 2017, type=RELEASE, libraries=[Library{name='com.mojang:patchy:1.1', rules=null, natives=null, extract=null}, Library{name='oshi-project:oshi-core:1.1', rules=null, natives=null, extract=null}, Library{name='net.java.dev.jna:jna:4.4.0', rules=null, natives=null, extract=null}, Library{name='net.java.dev.jna:platform:3.4.0', rules=null, natives=null, extract=null}, Library{name='com.ibm.icu:icu4j-core-mojang:51.2', rules=null, natives=null, extract=null}, Library{name='net.sf.jopt-simple:jopt-simple:5.0.3', rules=null, natives=null, extract=null}, Library{name='com.paulscode:codecjorbis:20101023', rules=null, natives=null, extract=null}, Library{name='com.paulscode:codecwav:20101023', rules=null, natives=null, extract=null}, Library{name='com.paulscode:libraryjavasound:20101123', rules=null, natives=null, extract=null}, Library{name='com.paulscode:librarylwjglopenal:20100824', rules=null, natives=null, extract=null}, Library{name='com.paulscode:soundsystem:20120107', rules=null, natives=null, extract=null}, Library{name='io.netty:netty-all:4.1.9.Final', rules=null, natives=null, extract=null}, Library{name='com.google.guava:guava:21.0', rules=null, natives=null, extract=null}, Library{name='org.apache.commons:commons-lang3:3.5', rules=null, natives=null, extract=null}, Library{name='commons-io:commons-io:2.5', rules=null, natives=null, extract=null}, Library{name='commons-codec:commons-codec:1.10', rules=null, natives=null, extract=null}, Library{name='net.java.jinput:jinput:2.0.5', rules=null, natives=null, extract=null}, Library{name='net.java.jutils:jutils:1.0.0', rules=null, natives=null, extract=null}, Library{name='com.google.code.gson:gson:2.8.0', rules=null, natives=null, extract=null}, Library{name='com.mojang:authlib:1.5.25', rules=null, natives=null, extract=null}, Library{name='com.mojang:realms:1.10.22', rules=null, natives=null, extract=null}, Library{name='org.apache.commons:commons-compress:1.8.1', rules=null, natives=null, extract=null}, Library{name='org.apache.httpcomponents:httpclient:4.3.3', rules=null, natives=null, extract=null}, Library{name='commons-logging:commons-logging:1.1.3', rules=null, natives=null, extract=null}, Library{name='org.apache.httpcomponents:httpcore:4.3.2', rules=null, natives=null, extract=null}, Library{name='it.unimi.dsi:fastutil:7.1.0', rules=null, natives=null, extract=null}, Library{name='org.apache.logging.log4j:log4j-api:2.8.1', rules=null, natives=null, extract=null}, Library{name='org.apache.logging.log4j:log4j-core:2.8.1', rules=null, natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives={LINUX=natives-linux, OSX=natives-osx, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@4dde1077}, Library{name='org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives={LINUX=natives-linux, OSX=natives-osx, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@64dbd7b2}, Library{name='net.java.jinput:jinput-platform:2.0.5', rules=null, natives={LINUX=natives-linux, OSX=natives-osx, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@38deb06b}, Library{name='com.mojang:text2speech:1.10.3', rules=null, natives=null, extract=null}, Library{name='com.mojang:text2speech:1.10.3', rules=null, natives={LINUX=natives-linux, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@227af47e}, Library{name='ca.weblite:java-objc-bridge:1.0.0', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives={OSX=natives-osx}, extract=com.mojang.launcher.versions.ExtractRules@1f9a15ee}, Library{name='ca.weblite:java-objc-bridge:1.0.0', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}], mainClass='net.minecraft.client.main.Main', jar='null', minimumLauncherVersion=18}
[14:26:22 INFO]: Installed CompleteVersion{id='1.12.2', updatedTime=Mon Sep 18 04:39:46 EDT 2017, releasedTime=Mon Sep 18 04:39:46 EDT 2017, type=RELEASE, libraries=[Library{name='com.mojang:patchy:1.1', rules=null, natives=null, extract=null}, Library{name='oshi-project:oshi-core:1.1', rules=null, natives=null, extract=null}, Library{name='net.java.dev.jna:jna:4.4.0', rules=null, natives=null, extract=null}, Library{name='net.java.dev.jna:platform:3.4.0', rules=null, natives=null, extract=null}, Library{name='com.ibm.icu:icu4j-core-mojang:51.2', rules=null, natives=null, extract=null}, Library{name='net.sf.jopt-simple:jopt-simple:5.0.3', rules=null, natives=null, extract=null}, Library{name='com.paulscode:codecjorbis:20101023', rules=null, natives=null, extract=null}, Library{name='com.paulscode:codecwav:20101023', rules=null, natives=null, extract=null}, Library{name='com.paulscode:libraryjavasound:20101123', rules=null, natives=null, extract=null}, Library{name='com.paulscode:librarylwjglopenal:20100824', rules=null, natives=null, extract=null}, Library{name='com.paulscode:soundsystem:20120107', rules=null, natives=null, extract=null}, Library{name='io.netty:netty-all:4.1.9.Final', rules=null, natives=null, extract=null}, Library{name='com.google.guava:guava:21.0', rules=null, natives=null, extract=null}, Library{name='org.apache.commons:commons-lang3:3.5', rules=null, natives=null, extract=null}, Library{name='commons-io:commons-io:2.5', rules=null, natives=null, extract=null}, Library{name='commons-codec:commons-codec:1.10', rules=null, natives=null, extract=null}, Library{name='net.java.jinput:jinput:2.0.5', rules=null, natives=null, extract=null}, Library{name='net.java.jutils:jutils:1.0.0', rules=null, natives=null, extract=null}, Library{name='com.google.code.gson:gson:2.8.0', rules=null, natives=null, extract=null}, Library{name='com.mojang:authlib:1.5.25', rules=null, natives=null, extract=null}, Library{name='com.mojang:realms:1.10.22', rules=null, natives=null, extract=null}, Library{name='org.apache.commons:commons-compress:1.8.1', rules=null, natives=null, extract=null}, Library{name='org.apache.httpcomponents:httpclient:4.3.3', rules=null, natives=null, extract=null}, Library{name='commons-logging:commons-logging:1.1.3', rules=null, natives=null, extract=null}, Library{name='org.apache.httpcomponents:httpcore:4.3.2', rules=null, natives=null, extract=null}, Library{name='it.unimi.dsi:fastutil:7.1.0', rules=null, natives=null, extract=null}, Library{name='org.apache.logging.log4j:log4j-api:2.8.1', rules=null, natives=null, extract=null}, Library{name='org.apache.logging.log4j:log4j-core:2.8.1', rules=null, natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives={LINUX=natives-linux, OSX=natives-osx, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@64fb5d1c}, Library{name='org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}, Library{name='org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives={LINUX=natives-linux, OSX=natives-osx, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@3c517f7b}, Library{name='net.java.jinput:jinput-platform:2.0.5', rules=null, natives={LINUX=natives-linux, OSX=natives-osx, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@6d1b5c17}, Library{name='com.mojang:text2speech:1.10.3', rules=null, natives=null, extract=null}, Library{name='com.mojang:text2speech:1.10.3', rules=null, natives={LINUX=natives-linux, WINDOWS=natives-windows}, extract=com.mojang.launcher.versions.ExtractRules@5a99a5c6}, Library{name='ca.weblite:java-objc-bridge:1.0.0', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives={OSX=natives-osx}, extract=com.mojang.launcher.versions.ExtractRules@64341034}, Library{name='ca.weblite:java-objc-bridge:1.0.0', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null', arch='null'}, features=null}], natives=null, extract=null}], mainClass='net.minecraft.client.main.Main', jar='null', minimumLauncherVersion=18}
[14:26:22 INFO]: Loaded 1 profile(s); selected 'SkyFactory 4 (2)'
[14:26:22 INFO]: Refreshing auth...
[14:26:22 INFO]: Logging in with access token

* Client/Server Log:
* Crash Log:

## World Information

* Preset:N/A

* Prestige: no
1.14.something
* Modpack Version world created in:

* Additional Content Installed:

## Client Information

7000 mb
* Modpack Version:1.14
* Java Version:1.12
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:single player
* Optifine Installed:idk
* Shaders Enabled:idk

**Comment by sk2048** [comment]
Minecraft 1.12 (which is what SkyFactory 4 uses) does not support Java later than version 8. You are using version 11. You need to get the correct version of Java.
