### ISSUE TITLE
Parabox world not collapsing on multiplayer world

### ISSUE THREAD

**Issue by LordZardeck** [DarkPacks/SkyFactory-4#1185]
## Bug Report

When I a vote occurs to close the loop on the parabox, I'm kicked and a message appears that the world is collapsing as expected, however, nothing happens and I can log back into the server immediately. I checked the server console, and the following is logged:

```
LordZardeck has voted to collapse the world!
All players have voted.
LordZardeck lost connection: The world is collapsing!
LordZardeck left the game
Server thread/FATAL 10:14:49
Error executing task
Console 10:14:49
java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_222]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_222]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_222]
at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_222]
at net.darkhax.parabox.util.WorldSpaceTimeManager.triggerCollapse(WorldSpaceTimeManager.java:110) ~[WorldSpaceTimeManager.class:?]
at net.darkhax.parabox.handler.VotingHandler.voteCollapse(VotingHandler.java:53) ~[VotingHandler.class:?]
at net.darkhax.parabox.network.PacketConfirmReset.getAction(PacketConfirmReset.java:29) ~[PacketConfirmReset.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_222]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
... 5 more
Server thread/WARN 10:14:49
handleDisconnection() called twice
Server thread/INFO 10:14:49
All players have gone offline. Ticket is scheduled to expire at world time 10908511
```

## Expected Behaviour

Loop would be closed, server would restart?, and parabox would be deactivated with prestige points given.

## World Information

* Preset: SkyBlock

* Prestige: Yes

* Modpack Version world created in: 4.0.8

## Client Information

* Modpack Version: 4.0.8
* Java Version: Don't know
* Launcher Used: Twitch
* Memory Allocated: 6698MB
* Server/LAN/Single Player: Server
* Optifine Installed: Yes 
* Shaders Enabled: No

## Server Information
* Java Version:
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```
* Operating System: Ubuntu
* Hoster/Hosting Solution: Private
* Sponge (Non-Vanilla Forge) Server: No

**Comment by LordZardeck** [comment]
So after a restart, the Parabox started working correctly. However, almost a week later, it's stopped working again with the same error
