### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by thorj016** [DarkPacks/SkyFactory-4#1251]
I am getting a crash on every world loading. both new worlds and my 3 pre-existing worlds all the same error. tried on normal skyblock 4, village, and skydome type worlds. also tried with prestige enabled and disabled.

Honestly not sure why this started as it was working fine yesterday and no updates since then, I did unlock something on prestige but can't remember what it was and can't check it. All I remember is that it was a 1 point cost thing and was my 3rd point.

https://pastebin.com/aRLnuGdA

**Comment by joernott** [comment]
I had a similar issue, which I solved by upgrading mcjtylib to 3.5.4 and dependend mods (xnet 1.8.2 and rftoolspower 1.2.0) manually. My NullPointer issue was on some other thing than the sky color though.

**Comment by ktole1999** [comment]
updating mods manually could break the pack and you wont get support for manually updated packs.

**Comment by joernott** [comment]
@ktole1999, I have built my own modpacks, so I assume, I know what I am doing. Facing the alternative of waiting for months until the modpack gets updated, was no viable alternative. So far, the worst thing that happened to me was that the manually replaced mods were not updated properly, resulting in two mod files with the same name but different versions or that a mod was downgraded by the "update". Both are fairly trivial issues to fix if you know what you're doing. Of course, if you don't, you should keep your hands off.

**Comment by ktole1999** [comment]
I never said you didnt know what you were doing. I was just stating the disclaimer regarding your comment since it could have led the op to manually updating his pavk and causing more issues.

Chill out



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by kylev** [comment]
I'm getting xnet errors on my world. I believe a version bump would get me back into my world, which I'd really appreciate. Looks like[ it has been fixed as of xnet 1.8.2](https://github.com/McJtyMods/XNet/issues/362).

Thanks!

```
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at mcjty.xnet.apiimpl.fluids.FluidChannelSettings.insertFluidReal(FluidChannelSettings.java:238) ~[FluidChannelSettings.class:?]
	at mcjty.xnet.apiimpl.fluids.FluidChannelSettings.tick(FluidChannelSettings.java:144) ~[FluidChannelSettings.class:?]
	at mcjty.xnet.blocks.controller.TileEntityController.func_73660_a(TileEntityController.java:250) ~[TileEntityController.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1835) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
```

**Comment by wkokwlewew** [comment]
i have been haveing the problum too
