### ISSUE TITLE
Crashing || Never played before

### ISSUE THREAD

**Issue by 9iy** [DarkPacks/SkyFactory-4#1463]
This was the error

[19/5/2020 21:47:23 PM] Exception in thread "main" [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: scala/Function1
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.getConstructor0(Unknown Source)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at $wrapper.li.cil.oc.common.asm.ClassTransformer.<init>(Unknown Source)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: scala.Function1
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19/5/2020 21:47:23 PM] [21:47:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 15 more

I have no idea what this means but help

**Comment by sam-kirby** [comment]
Missing libraries. No idea what to recommend though as I don't know which launcher you're using, or even if this is a server or a client.
