### ISSUE TITLE
Java/ATL Problem

### ISSUE THREAD

**Issue by m0istn00dl** [DarkPacks/SkyFactory-4#1670]
I can't seem to install anything on ATLauncher, modpack or otherwise. If I do manage to (which is rare) it fails to run due to errors it lists as "missing mod dependencies". I have no idea why this is, and have attempted to redownload Java multiple times. Here is the log copied from my attempt to download Vanilla Minecraft with Forge:
[30/9/2020 17:41:49 PM] Console Cleared
[30/9/2020 17:43:42 PM] Started install of Vanilla Minecraft With Forge version 1.16.3
[30/9/2020 17:43:42 PM] Using loader version 34.1.1
[30/9/2020 17:44:05 PM] java.net.SocketTimeoutException: timeout

	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:642)

	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:651)

	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:141)

	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:99)

	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:105)

	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:82)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)

	at com.atlauncher.Network.lambda$createProgressClient$1(Network.java:61)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)

	at com.atlauncher.network.ErrorReportingInterceptor.intercept(ErrorReportingInterceptor.java:32)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)

	at com.atlauncher.network.UserAgentInterceptor.intercept(UserAgentInterceptor.java:34)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)

	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)

	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)

	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)

	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)

	at com.atlauncher.network.DebugLoggingInterceptor.intercept(DebugLoggingInterceptor.java:37)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)

	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)

	at okhttp3.RealCall.execute(RealCall.kt:66)

	at com.atlauncher.network.Download.execute(Download.java:258)

	at com.atlauncher.network.Download.getHashFromURL(Download.java:291)

	at com.atlauncher.network.Download.getHash(Download.java:308)

	at com.atlauncher.network.Download.downloadFile(Download.java:520)

	at com.atlauncher.data.minecraft.loaders.forge.ForgeLoader.downloadAndExtractInstaller(ForgeLoader.java:129)

	at com.atlauncher.workers.InstanceInstaller.downloadLoader(InstanceInstaller.java:338)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:208)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:94)

	at javax.swing.SwingWorker$1.call(Unknown Source)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at javax.swing.SwingWorker.run(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

[30/9/2020 17:44:05 PM] Failed to download file **USERSDIR**\loaders\forge-1.16.3-34.1.1-installer.jar
[30/9/2020 17:44:05 PM] java.io.IOException: closed

	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:434)

	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Unknown Source)

	at sun.nio.ch.FileChannelImpl.transferFromArbitraryChannel(Unknown Source)

	at sun.nio.ch.FileChannelImpl.transferFrom(Unknown Source)

	at com.atlauncher.network.Download.downloadDirect(Download.java:387)

	at com.atlauncher.network.Download.downloadFile(Download.java:524)

	at com.atlauncher.data.minecraft.loaders.forge.ForgeLoader.downloadAndExtractInstaller(ForgeLoader.java:129)

	at com.atlauncher.workers.InstanceInstaller.downloadLoader(InstanceInstaller.java:338)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:208)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:94)

	at javax.swing.SwingWorker$1.call(Unknown Source)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at javax.swing.SwingWorker.run(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

[30/9/2020 17:44:05 PM] org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip file is empty

	at org.zeroturnaround.zip.ZipExceptionUtil.rethrow(ZipExceptionUtil.java:11)

	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:522)

	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:472)

	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:996)

	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:939)

	at com.atlauncher.network.Download.runPostProcessors(Download.java:587)

	at com.atlauncher.network.Download.downloadFile(Download.java:576)

	at com.atlauncher.data.minecraft.loaders.forge.ForgeLoader.downloadAndExtractInstaller(ForgeLoader.java:129)

	at com.atlauncher.workers.InstanceInstaller.downloadLoader(InstanceInstaller.java:338)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:208)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:94)

	at javax.swing.SwingWorker$1.call(Unknown Source)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at javax.swing.SwingWorker.run(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

Caused by: java.util.zip.ZipException: zip file is empty

	at java.util.zip.ZipFile.open(Native Method)

	at java.util.zip.ZipFile.<init>(Unknown Source)

	at java.util.zip.ZipFile.<init>(Unknown Source)

	at java.util.zip.ZipFile.<init>(Unknown Source)

	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:496)

	... 15 more

[30/9/2020 17:44:14 PM] Copied Log to clipboard

**Comment by m0istn00dl** [comment]
I apologize if past issue posts were poorly worded and framed, and any spamming was due to my misunderstanding of the bot's actions.

**Comment by sam-kirby** [comment]
This is the issue page for SkyFactory 4, a 1.12.2 modpack that has been released on Curseforge and ATLauncher.

You are having an issue with ATLauncher, not SkyFactory 4. We do not make ATLauncher. There is nothing we can reasonably do to help you with this.

As I have said before, please seek support from ATLauncher's developers or use a different launcher to play SkyFactory 4. You can use any of the following instead of ATLauncher.
- The Twitch Launcher
- MultiMC
- GDLauncher

You can contact ATLauncher's developers at the following link:
https://github.com/ATLauncher/ATLauncher/issues

This is the 5th time you have reported this issue to us. Please do not do so again.
