### ISSUE TITLE
LIsten to the logs

### ISSUE THREAD

**Issue by jarn123** [DarkPacks/SkyFactory-4#1688]
## Bug Description
 the log says "

[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: The following texture errors were found.
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: ==================================================
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:   DOMAIN matteroverdrive
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: --------------------------------------------------
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:   domain matteroverdrive is missing 1 texture
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:     domain matteroverdrive has 1 location:
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:       mod matteroverdrive resources at C:\Users\.............\Twitch\Minecraft\Instances\SkyFactory 4 (2)\mods\MatterOverdrive-1.12.2-0.7.1.0-universal.jar
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: -------------------------
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:     The missing resources for domain matteroverdrive are:
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:       textures/gui/items/minimap_target.png
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: -------------------------
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:     No other errors exist for domain matteroverdrive
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: ==================================================
[18:15:50] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: 

"   and more log "

18:16:00] [Client thread/ERROR] [FML]: Unidentified mapping from registry minecraft:recipes
[18:16:00] [Client thread/ERROR] [FML]:     nuclearcraft:item.biblioglasses.readingglasses_2: 7781
[18:16:00] [Client thread/ERROR] [FML]:     nuclearcraft:item.biblioglasses.readingglasses_1: 7780
[18:16:00] [Client thread/ERROR] [FML]:     nuclearcraft:item.biblioglasses.readingglasses: 7779

"   and look at how big this warn is and this keeps happening "

[18:16:19] [Client thread/WARN] [jei]: Mod added a tree entry after memory optimization!
java.lang.UnsupportedOperationException: null
	at it.unimi.dsi.fastutil.chars.AbstractChar2ObjectFunction.put(AbstractChar2ObjectFunction.java:119) ~[fastutil-7.1.0.jar:?]
	at mezz.jei.suffixtree.Node.addEdge(Node.java:124) [Node.class:?]
	at mezz.jei.suffixtree.GeneralizedSuffixTree.testAndSplit(GeneralizedSuffixTree.java:225) [GeneralizedSuffixTree.class:?]
	at mezz.jei.suffixtree.GeneralizedSuffixTree.update(GeneralizedSuffixTree.java:364) [GeneralizedSuffixTree.class:?]
	at mezz.jei.suffixtree.GeneralizedSuffixTree.put(GeneralizedSuffixTree.java:166) [GeneralizedSuffixTree.class:?]
	at mezz.jei.ingredients.IngredientFilter.addIngredient(IngredientFilter.java:119) [IngredientFilter.class:?]
	at mezz.jei.ingredients.IngredientRegistry.addIngredientsAtRuntime(IngredientRegistry.java:277) [IngredientRegistry.class:?]
	at mezz.jei.ingredients.IngredientRegistry.addIngredientsAtRuntime(IngredientRegistry.java:222) [IngredientRegistry.class:?]
	at mezz.jei.ingredients.IngredientRegistry.addIngredientsAtRuntime(IngredientRegistry.java:229) [IngredientRegistry.class:?]
	at li.cil.oc.integration.jei.ModJEI$$anonfun$addDiskAtRuntime$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(ModJEI.scala:27) [ModJEI$$anonfun$addDiskAtRuntime$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.class:?]
	at li.cil.oc.integration.jei.ModJEI$$anonfun$addDiskAtRuntime$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(ModJEI.scala:27) [ModJEI$$anonfun$addDiskAtRuntime$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.class:?]
	at scala.Option.foreach(Option.scala:245) [Option.class:?]
	at li.cil.oc.integration.jei.ModJEI$$anonfun$addDiskAtRuntime$1$$anonfun$apply$1.apply$mcV$sp(ModJEI.scala:27) [ModJEI$$anonfun$addDiskAtRuntime$1$$anonfun$apply$1.class:?]
	at li.cil.oc.common.EventHandler$$anonfun$onClientTick$1.apply(EventHandler.scala:239) [EventHandler$$anonfun$onClientTick$1.class:?]
	at li.cil.oc.common.EventHandler$$anonfun$onClientTick$1.apply(EventHandler.scala:238) [EventHandler$$anonfun$onClientTick$1.class:?]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [IndexedSeqOptimized$class.class:?]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [scala-library-2.11.1.jar:?]
	at li.cil.oc.common.EventHandler$.onClientTick(EventHandler.scala:238) [EventHandler$.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2207_EventHandler$_onClientTick_ClientTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
"
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version: 4.2.2
* Java Version:
* Launcher Used: minecraft
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
This is unhelpful.
