### ISSUE TITLE
l have problem to open server in Debian

### ISSUE THREAD

**Issue by DIDIZera** [DarkPacks/SkyFactory-4#1725]
### l downloaded a Server Pack, l ran the Install.sh , when l run ServerStart.sh l have a problem:
```
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.n
et.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loa
der 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
```

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.9+11-post-Debian-1deb10u1, mixed mode, sharing)

* Operating System:
Debian 4.19.152-1 (2020-10-18) x86_64

* Hoster/Hosting Solution:
Google Cloud Platform

* Sponge (Non-Vanilla Forge) Server:

![](https://cdn.discordapp.com/attachments/737761117480419489/777295912946630677/unknown.png)

**Comment by sam-kirby** [comment]
You must use Java 8 (Hotspot VM) when running a modded Minecraft server for 1.12.2. Changes to reflection in 9 and beyond render them incompatible.

**Comment by sam-kirby** [comment]
Steps given here for Ubuntu should be broadly similar for Debian, though note the package name may be different: https://github.com/DarkPacks/SevTech-Ages/issues/4381#issuecomment-723568552

**Comment by DIDIZera** [comment]
@sam-kirby thanks for help l solved
