### ISSUE TITLE
Can't start the server in a linux terminal server

### ISSUE THREAD

**Issue by Aarou1** [DarkPacks/SkyFactory-4#1757]
## Bug Description

I can't open the server on a linux server. Getting a error message:
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

### Did this behavior use to work in the previous version?

First time testing.

## Steps to Reproduce (for bugs)

1. Do a clean install of the server pack
2. Run the Install.sh
3. Run the ServerStart.sh

## Logs

* Client/Server Log: Didn't see the log file
* Crash Log: Didn't see this one either

## World Information
* World Preset: Default
* Prestige Enabled: Default
* Modpack Version world created in:4.2.2
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version: Not sure
* Operating System: Debian
* Hoster/Hosting Solution: Google Virtual Server
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
You must use Java 8. This is a limitation of Forge for Minecraft 1.12.2.

**Comment by Aarou1** [comment]
Do you know how can I get it?

**Comment by sam-kirby** [comment]
Java 8 is no longer in Debian's repos, so you need to add a source for it. Adoptopenjdk maintains an apt repo containing Java 8.

First you need to determine the code name of the Debian installation; run the following command to determine it if you don't already know:

```sh
cat /etc/os-release | grep VERSION_CODENAME
```

You also need to make sure you have the necessary software installed for adding the signing key used by the repo:

```sh
sudo apt install wget apt-transport-https gnupg
```

To add adoptopenjdk's repo, run the following commands, making sure to fill in your code name where there is a placeholder in the second command.

```sh
wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -

echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb <codename> main" | sudo tee /etc/apt/sources.list.d/adoptopenjdk.list

sudo apt update
```

Then install it by running

```sh
sudo apt install adoptopenjdk-8-hotspot
```

Finally, set it as the default Java by running

```sh
sudo update-alternatives --config java
```

And select it from the list of available Java installations.

Alternatively, if you don't want it to be the default Java, modify the start script to use its absolute path.

These instructions are taken from https://adoptopenjdk.net/installation.html#installers
