### ISSUE TITLE
Server crashing on startup

### ISSUE THREAD

**Issue by Pointdroid** [DarkPacks/SkyFactory-4#1842]
Hello!

My server crashes almost instantly I open it.
A comand promt window opens and instantly closes.
No log files are made.

 Steps to Reproduce 
1. Open install.bat
2. Open serverstart.bat

Logs
Starting Sky Factory 4 Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

Modpack Version: 4.2.2
Java Version:15.0.1
Memory Allocated: 4gb
Operating System: Windows 10 64bit

**Comment by sam-kirby** [comment]
Java 15 is not supported by Forge for 1.12.2 and below. To play this pack, you must use Java 8.
