### ISSUE TITLE
Trying to craft a crafting wireless terminal crash the game

### ISSUE THREAD

**Issue by SoftGuardian** [DarkPacks/SkyFactory-4#1989]
## Bug Description
Whenever I try to put a ME crafting terminal with a universal wireless termnial in any crafting GUI the game crashes

### Did this behavior use to work in the previous version?
This is the only version I've played skyfactory in

## Steps to Reproduce (for bugs)
1. Crafting a normal wireless terminal
2. Giving it Gas terminal so it becomes universal for items and gases
3. Trying to put it with a crafting terminal in any crafting grid will crash the game

## Logs
// Ooh. Shiny.

Time: 11/2/21 11:44 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at extracells.item.ItemWirelessTerminalUniversal.isInstalled(ItemWirelessTerminalUniversal.scala:219)
	at extracells.util.recipe.RecipeUniversalTerminal$$anonfun$matches$2.apply(RecipeUniversalTerminal.scala:66)
	at extracells.util.recipe.RecipeUniversalTerminal$$anonfun$matches$2.apply(RecipeUniversalTerminal.scala:65)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at extracells.util.recipe.RecipeUniversalTerminal$.func_77569_a(RecipeUniversalTerminal.scala:65)
	at net.minecraft.item.crafting.CraftingManager.func_192413_b(CraftingManager.java:213)
	at appeng.container.implementations.ContainerCraftingTerm.func_75130_a(ContainerCraftingTerm.java:92)
	at appeng.container.slot.SlotCraftingMatrix.func_75215_d(SlotCraftingMatrix.java:53)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at appeng.client.gui.AEBaseGui.func_184098_a(AEBaseGui.java:596)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at appeng.client.gui.AEBaseGui.func_146274_d(AEBaseGui.java:671)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at extracells.item.ItemWirelessTerminalUniversal.isInstalled(ItemWirelessTerminalUniversal.scala:219)
	at extracells.util.recipe.RecipeUniversalTerminal$$anonfun$matches$2.apply(RecipeUniversalTerminal.scala:66)
	at extracells.util.recipe.RecipeUniversalTerminal$$anonfun$matches$2.apply(RecipeUniversalTerminal.scala:65)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at extracells.util.recipe.RecipeUniversalTerminal$.func_77569_a(RecipeUniversalTerminal.scala:65)
	at net.minecraft.item.crafting.CraftingManager.func_192413_b(CraftingManager.java:213)
	at appeng.container.implementations.ContainerCraftingTerm.func_75130_a(ContainerCraftingTerm.java:92)
	at appeng.container.slot.SlotCraftingMatrix.func_75215_d(SlotCraftingMatrix.java:53)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at appeng.client.gui.AEBaseGui.func_184098_a(AEBaseGui.java:596)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at appeng.client.gui.AEBaseGui.func_146274_d(AEBaseGui.java:671)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: appeng.client.gui.implementations.GuiCraftingTerm

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['HairyFlairy'/71, l='MpServer', x=17.14, y=66.00, z=3.65]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 11 - topography, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (3,73,3), Chunk: (at 3,4,3 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2462084 game time, 4105537 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 27 total; [EntityVillagerMadScientist['Mad Scientist Junkie'/5, l='MpServer', x=0.72, y=66.00, z=18.74], EntityChicken['Chicken'/6, l='MpServer', x=-13.20, y=65.84, z=-12.50], EntityCow['Cow'/8, l='MpServer', x=6.19, y=66.00, z=4.45], EntityChicken['Chicken'/9, l='MpServer', x=-14.49, y=66.00, z=-3.16], EntityCow['Cow'/20, l='MpServer', x=-16.49, y=65.00, z=-11.23], EntityFancyItemFrame['Clear Item Frame'/21, l='MpServer', x=22.97, y=66.50, z=-0.50], EntityFancyItemFrame['Clear Item Frame'/22, l='MpServer', x=22.97, y=66.50, z=-2.50], EntityPlayerSP['HairyFlairy'/71, l='MpServer', x=17.14, y=66.00, z=3.65], EntityFancyItemFrame['Clear Item Frame'/23, l='MpServer', x=22.97, y=66.50, z=-3.50], EntityFancyItemFrame['Clear Item Frame'/24, l='MpServer', x=22.97, y=66.50, z=-1.50], EntityItem['item.item.egg'/38104, l='MpServer', x=-13.13, y=65.00, z=-12.38], EntityWitherSkeleton['The Guard'/25, l='MpServer', x=19.06, y=66.00, z=-3.08], EntityChicken['Chicken'/26, l='MpServer', x=23.10, y=63.00, z=-5.43], EntityFancyItemFrame['Clear Item Frame'/27, l='MpServer', x=22.97, y=66.50, z=2.50], EntityFancyItemFrame['Clear Item Frame'/28, l='MpServer', x=22.97, y=66.50, z=5.50], EntityFancyItemFrame['Clear Item Frame'/29, l='MpServer', x=22.97, y=66.50, z=4.50], EntityFancyItemFrame['Clear Item Frame'/30, l='MpServer', x=22.97, y=66.50, z=7.50], EntityFancyItemFrame['Clear Item Frame'/31, l='MpServer', x=22.97, y=66.50, z=6.50], EntityFancyItemFrame['Clear Item Frame'/32, l='MpServer', x=22.97, y=66.50, z=8.50], EntityFancyItemFrame['Clear Item Frame'/33, l='MpServer', x=22.97, y=66.50, z=9.50], EntityItem['item.item.egg'/38113, l='MpServer', x=22.22, y=63.00, z=-5.69], EntityFancyItemFrame['Clear Item Frame'/34, l='MpServer', x=22.97, y=66.50, z=10.50], EntityFancyItemFrame['Clear Item Frame'/35, l='MpServer', x=22.97, y=66.50, z=0.50], EntityFancyItemFrame['Clear Item Frame'/36, l='MpServer', x=22.97, y=66.50, z=1.50], EntityItem['item.item.egg'/38116, l='MpServer', x=-13.85, y=66.00, z=-2.69], EntityFancyItemFrame['Clear Item Frame'/37, l='MpServer', x=22.97, y=66.50, z=3.50], EntityLatchedRenderer['unknown'/38003, l='MpServer', x=17.14, y=66.00, z=3.65]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## World Information
* World Preset: Tutorial
* Prestige Enabled: No
* Modpack Version world created in: 4.2.2
* Additional Content Installed: No

## Client Information
* Modpack Version: 4.2.2
* Java Version: Latest
* Launcher Used: MC Launcher
* Memory Allocated: 9GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by SoftGuardian** [comment]
Ok then

**Comment by cupymanor** [comment]
That's fucking retarded
