### ISSUE TITLE
Server crash: `launcher.java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by TheoCGaming** [DarkPacks/SkyFactory-4#2164]
## Bug Description

The server crashes with an "InvocationTargetException" on startup from ServerStart.sh, but running the server jar directly goes without issue (but probably doesn't run SF4)

### Did this behavior use to work in the previous version?

Unknown

## Steps to Reproduce (for bugs)

1. Attempt to run the server jar (?)
2. Run ServerStart.sh
3. 

## Logs

* Client/Server Log:
None given
* Crash Log:
Note: I was onlly able to get the log to show in `stdout` and `stderr`.
```
Starting Sky Factory 4 Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
```
## World Information
* World Preset: Default
* Prestige Enabled: Default
* Modpack Version world created in: 4.2.4
* Additional Content Installed: None

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version: 18 (I can't change to java 8 for unknown reasons.)
* Operating System: Arch Linux with KDE Desktop
* Hoster/Hosting Solution: Self
* Sponge (Non-Vanilla Forge) Server: Unknown, likely vanilla forge.

**Comment by TheoCGaming** [comment]
> This issue is being automatically closed because it does not follow the issue template.

what? I followed it as closely as I could! ~~this is why you don't use bots to manage things~~

**Comment by sam-kirby** [comment]
We receive a large proportion of low effort issue reports from which we are not able to take meaningful action; the bot is sufficient for this and often prompts people to provide the necessary information. It only looks at the headings present in the issue report, and in this case it appears to have failed to notice the world information heading due to the presence of a code block without a line break. This is why we still review all reports manually.

Regardless, this is not an issue with the pack and so had it not been closed by the bot, I would be closing it now. You must use Java 8 with any Forge packs for 1.12.2 and this pack is no exception. This is due to a change in how reflection works in Java 9+. You say you can't use Java 8, but provide no explanation as to why. In case you just don't know how, I'll provide a quick overview of the steps to use Java 8 on Arch.

Java 8 is packaged in the extra repository, the package name is `﻿﻿jre8-openjdk`. Install using `sudo pacman -S jre8-openjdk` or use your wrapper of choice.

Once installed, you can set it as default using `archlinux-java` as follows: `sudo archlinux-java set java-8-openjdk`, and you can return to using Java 18 by running `sudo archlinux-java set java-18-openjdk`.

Running `java -version` should confirm you're using Java 8.

If you need further support you can ask here or on Discord at https://discord.gg/darkosto
