### ISSUE TITLE
First starting a server from the .bat doesn't work

### ISSUE THREAD

**Issue by M43iX** [DarkPacks/SkyFactory-4#2201]
## Bug Description
Starting the server from the .bat doesn't work, throwing an InvocationTargetException. This is the cmd output (added a pause line for debugging)

Starting Sky Factory 4 Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

I followed the instraction excecuting install.bat and set eula to true. No crash log generated of course.

**Comment by sam-kirby** [comment]
You must use Java 8 with any 1.12.2 packs - this is a limitation of Forge.

This error occurs if you try to start the pack with a newer version of Java set as your default.
