### ISSUE TITLE
Server files looks weird ?

### ISSUE THREAD

**Issue by DrKnoll** [DarkPacks/SkyFactory-4#2209]
## Bug Description

Hi guys, how is everyone ? ^^ Well.. I recently got the last version of sky factory 4 ( 4.2.4 ) + it's server files ; I can open the game without any problems and play alone BUT when i open the server , i can start the '' install '' button that got me Forge 1.12.2.14.23.5.28.60 + 1.12.2.14.23.5.28.60-installer and 1.12.2.14.23.5.28.60-installer.jar
Compared to other people ( While looking to fix this error, i didn't had the '' Universal '' file, is it normal ? 

Next is when i click on the ServerStart button, the cmd crash instantly with this error : 
Starting Sky Factory 4 Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more

BUT when i click on the '' Minecraft_server.1.12.2 '' executable jar file, stuff pop and i can accept the '' EULA '' and start my server YET when i do it this way, i just get a regular default world spawn ??

In case you guys wonder, i did read the multiplayer pdf and i didn't touch the server option thingy, so it's still in : 
★ Sky Factory 4 Classic​: 
generator-settings={"Topography-Preset":"Sky Factory 4"} 
level-type=DEFAULT 

### Did this behavior use to work in the previous version?

<Well, i only played '' All the mods 8 server '' pack with a friend and never got any issues with it>

## Steps to Reproduce (for bugs)

<already explained ^^

## Logs

* Client/Server Log:
* Crash Log: 
* 
* Starting Sky Factory 4 Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more

## World Information
* World Preset:<generator-settings={"Topography-Preset":"Sky Factory 4"} >
* Prestige Enabled:<didn't touch it>
* Modpack Version world created in:<4.2.4>
* Additional Content Installed:<None>

## Client Information
* Modpack Version:<4.2.4>
* Java Version:<>
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:<in my java folder, it seems that i have 3 different ones : 17.0.2 / 18 / 8.0_301 >
* Operating System:<64bit>
* Hoster/Hosting Solution:<Hamachi>
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
From the sound of it, everything is fine with the server files. Forge got rid of the `-universal` suffix when they updated their build tools.

The issue seems to be that you're trying to use either Java 17 or 18 when Forge for 1.12.2 requires that you use Java 8.

This is apparent from your error as it mentions modules, which did not exist in Java 8.

There are several options for resolving this, the simplest is to remove the other versions of Java, although you may need them for other things such as packs using a more recent version of Minecraft.

Alternatively, you can modify the start script so it refers to Java 8 using an absolute path - e.g. replace `java` with `"C:\Program Files\Java\1.8.0_351\bin\java.exe"`

This path is an example only, but note that as it contains a space it has to appear in double quotes (`"`). Omitting these would lead to an error.

I'm going to close this issue as it does not represent a bug in the pack, but feel free to continue this thread if you need more help, or use the Discord server at https://discord.gg/darkosto
