### ISSUE TITLE
server.bat file wont open

### ISSUE THREAD

**Issue by Nightmare0099** [DarkPacks/SkyFactory-4#2332]
## Bug Description

 the server.bat file wont open i have already downloaded the latest version on java 

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:Starting Sky Factory 4 Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version: latest
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Your version of Java is too modern; this version of Minecraft Forge requires you use Java 8, which has no concept of modules.

Either uninstall this latest version of Java and install a 64-bit build of Java 8, or should you require the latest version of Java for other purposes you can install Java 8 alongside it and then modify the start script so that it uses this version by absolute path, an example of this is as follows (which you can copy and paste assuming the installation location matches):-

```bat

@echo off

call settings.bat

:start_server
echo Starting Server
"C:\Program Files\Java\jre-1.8\bin\java.exe" -Xms%MIN_RAM% -Xmx%MAX_RAM% %JAVA_PARAMETERS% -jar %SERVER_JAR% nogui
pause
exit /B

goto start_server
```
